name: extended_text
description: Extended official text to build special text like inline image or @somebody quickly,it also support custom background,custom over flow,gradient and custom selection toolbar and handles.
version: 15.0.1
repository: https://github.com/fluttercandies/extended_text
issue_tracker: https://github.com/fluttercandies/extended_text/issues
topics:
  - extended-text
  - custom-text-overflow
  - gradient-text

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  extended_text_library: ^12.0.1
    # version: ^11.0.0-dev.1
    # hosted: "https://pub.dev"
  flutter:
    sdk: flutter
# dependency_overrides:
#   extended_text_library:
#     path: ../extended_text_library
      
dev_dependencies:
  flutter_test:
    sdk: flutter


