name: extended_text
description: Extended official text to build special text like inline image or @somebody quickly,it also support custom background,custom over flow and custom selection toolbar and handles.
version: 5.0.0
homepage: https://github.com/fluttercandies/extended_text

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  extended_text_library: ^4.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


