name: extended_text
description: Extended official text to build special text like inline image or @somebody quickly,it also support custom background,custom over flow and custom selection toolbar and handles.
version: 11.0.1
homepage: https://github.com/fluttercandies/extended_text

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  extended_text_library: ^11.1.0
    # version: ^11.0.0-dev.1
    # hosted: "https://pub.dev"
  flutter:
    sdk: flutter
dependency_overrides:
  #extended_text_library:
    # git: 
    #   url: https://github.com/fluttercandies/extended_text_library.git
    #   ref: refactor
    #path: ../extended_text_library
      
dev_dependencies:
  flutter_test:
    sdk: flutter


